<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Application Form - {{ $form->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            font-size: 12px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #0056b3;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #0056b3;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .section-title {
            background-color: #f0f4f8;
            color: #0056b3;
            padding: 8px 15px;
            font-size: 14px;
            font-weight: bold;
            border-left: 4px solid #0056b3;
            margin-top: 20px;
            margin-bottom: 15px;
        }
        .field-row {
            margin-bottom: 8px;
            page-break-inside: avoid;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        .field-label {
            font-weight: bold;
            color: #555;
            width: 40%;
            display: inline-block;
            vertical-align: top;
        }
        .field-value {
            width: 58%;
            display: inline-block;
            color: #000;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Nursing College ERP</h1>
        <p>{{ $form->title }}</p>
        <p>Application Reference: #{{ str_pad($submission->id, 6, '0', STR_PAD_LEFT) }}</p>
        <p>Date: {{ $submission->created_at->format('d M, Y h:i A') }}</p>
    </div>

    @foreach($form->sections as $section)
        <div class="section">
            <div class="section-title">{{ $section->title }}</div>
            
            @foreach($section->fields as $field)
                @php
                    $value = $data[$field->name] ?? '-';
                    if(is_array($value)) {
                        $value = implode(', ', $value);
                    }
                    // If it's a file, we might want to show "Attached" or the filename
                    if ($field->field_type === 'file' && $value !== '-' && !empty($value)) {
                        $value = 'File Attached (' . basename($value) . ')';
                    }
                @endphp
                <div class="field-row">
                    <span class="field-label">{{ $field->label }}:</span>
                    <span class="field-value">{{ $value }}</span>
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by Nursing College ERP System | {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
